version: '3'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500
  mysql:
    image: 'mysql:latest'
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
  redis:
    image: 'redis:latest'
    ports:
      - 6378:6379
  nats:
    image: 'nats:latest'
    ports:
      - 4222:4222 # 客户端口
      - 8222:8222 # 服务端口
