version: '3.4'
services:
  consul:
    image: 'hashicorp/consul'
    ports:
      - 8500:8500

  mysql:
    image: 'mysql:latest'
    volumes:
      - ./deploy/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_proto
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: 'redis:latest'
    ports:
      - 6378:6379

  nats:
    image: 'nats:latest'
    ports:
      - 4222:4222 # 客户端口
      - 8222:8222 # 服务端口

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper


  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deploy/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  jaeger-all-in-one:
    container_name: jaeger-all-in-one
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  loki:
    image: grafana/loki:2.9.2
    volumes:
      - ./deploy/config/loki.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./deploy/config/promtail.yml:/etc/promtail/config.yml
      - ./app/frontend/log:/logs/frontend
    command: -config.file=/etc/promtail/config.yml

  frontend:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - SESSION_SECRET="SESSION_SECRET"
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
      - GO_ENV=test
    depends_on:
      - consul
      - redis
    volumes: # 挂载
      - ./app/frontend/conf/test:/opt/gomall/frontend/conf/test

  product:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc
      args:
        - SVC=product
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
#      - GO_ENV=test
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

    volumes: # 挂载
      - ./app/product/conf/test/:/opt/gomall/product/conf/test/

  cart:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc
      args:
        - SVC=cart
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy

    volumes: # 挂载
      - ./app/cart/conf/test/:/opt/gomall/cart/conf/test/

#  checkout:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=checkout
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3306
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
#      - OTL_EXPORTER_OTLP_INSECURE=true
#    depends_on:
#      consul:
#        condition: service_started
#      redis:
#        condition: service_started
#      mysql:
#        condition: service_healthy
#    volumes: # 挂载
#      - ./app/checkout/conf/test/:/opt/gomall/checkout/conf/test/

  payment:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc
      args:
        - SVC=payment
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes: # 挂载
      - ./app/payment/conf/test/:/opt/gomall/payment/conf/test/

  user:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc
      args:
        - SVC=user
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes: # 挂载
      - ./app/user/conf/test/:/opt/gomall/user/conf/test/

  email:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.svc
      args:
        - SVC=email
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
      - OTL_EXPORTER_OTLP_INSECURE=true
    depends_on:
      consul:
        condition: service_started
      redis:
        condition: service_started
      mysql:
        condition: service_healthy
    volumes: # 挂载
      - ./app/email/conf/test/:/opt/gomall/email/conf/test/

#  order:
#    build:
#      context: .
#      dockerfile: ./deploy/Dockerfile.svc
#      args:
#        - SVC=order
#    environment:
#      - MYSQL_USER=root
#      - MYSQL_PASSWORD=root
#      - MYSQL_HOST=mysql
#      - MYSQL_PORT=3306
#      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger-all-in-one:4317
#      - OTL_EXPORTER_OTLP_INSECURE=true
#    depends_on:
#      consul:
#        condition: service_started
#      redis:
#        condition: service_started
#      mysql:
#        condition: service_healthy
#    volumes: # 挂载
#      - ./app/order/conf/test/:/opt/gomall/order/conf/test/