kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: gomall-dev # 集群名字
nodes: # 一共3个节点
- role: control-plane # 控制面
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/init.sql
    containerPath: /opt/gomall/db/sql/init.sql
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config

- role: worker # 工作节点
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/init.sql
    containerPath: /opt/gomall/db/sql/init.sql
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config

# image for China: registry.cn-hangzhou.aliyuncs.com/kindest/node:v1.30.0
- role: worker
  image: kindest/node:v1.30.0
  extraMounts:
  - hostPath: ./db/sql/init.sql
    containerPath: /opt/gomall/db/sql/init.sql
  - hostPath: ./deploy/config
    containerPath: /opt/gomall/deploy/config
